import "./globals.css";
import Navbar from "../components/Navbar";
import { Toaster } from "sonner";


export const metadata = {
  title: "my-portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>

        <Navbar />
        {children}
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
